swig: Downgrade to v4.3.1
swig 4.4.0 results Python plugins not loading due to in the following
error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/share/kicad/scripting/kicad_pyshell/__init__.py", line 23, in <module>
    import pcbnew
  File "/app/lib/python3.13/site-packages/pcbnew.py", line 68, in <module>
    class SwigPyIterator(object):
    ...<76 lines>...
            return self
  File "/app/lib/python3.13/site-packages/pcbnew.py", line 76, in SwigPyIterator
    __swig_destroy__ = _pcbnew.delete_SwigPyIterator
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'moduledef' object has no attribute 'delete_SwigPyIterator'
```